# Generated by Django 3.2.1 on 2021-05-21 03:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pic.png', upload_to=account.models.user_directory_path),
        ),
    ]
